### ISSUE TITLE
Suggestion about boolToInt

### ISSUE THREAD

**Issue by MaxGraey** [ColinEberhardt/atari2600-wasm#3]
Hi, would like suggest replace:
```ts
const boolToInt = (value: boolean): u8 => (value ? 1 : 0);

...
```
to:
```ts
function boolToInt(value: boolean): u8 {
  return value ? 1 : 0;
}

let someCond = (x == 0);
let boolValue = boolToInt(someCond);
```
or even better to:
```ts
let someCond = (x == 0);
let boolValue = u8(someCond);
```
and remove `boolToInt` helper at all.

**Comment by ColinEberhardt** [comment]
Thanks @MaxGraey - that is very timely feedback as I have just [written a blog post](https://blog.scottlogic.com/2020/08/26/codegen-6502-webassembly.html) about this project :-)

I did spend some time yesterday exploring this problem - initially I noticed that whilst Visual Studio reported errors with this assignment:

~~~
let boolValue: u8 = x === 0;
~~~

> `Type 'boolean' is not assignable to type 'number' - ts(2322)`

The AssemblyScript compiler happily compiled this code and the functionality was as expected. I also checked the generated wasm code to verify that the code output from the following was the same:

~~~
let boolValue1: u8 = x === 0;
let boolValue2: u8 = x === 0 ? 1 : 0;
~~~

So my only reason for adding the `boolToInt` function was to keep Visual Studio happy! 

Thanks for pointing out the `u8` function, I've now updated the code to use that instead.

**Comment by MaxGraey** [comment]
> I also checked the generated wasm code to verify that the code output from the following was the same

This really true but for last version of AS due to optimization `cond ? 1 : 0` [was recently added](https://github.com/WebAssembly/binaryen/pull/2869)
